/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ntkrqakwzwlybrcwchyt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50a3JxYWt3endseWJyY3djaHl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxMjEyNzgsImV4cCI6MjA4NTY5NzI3OH0.E7D3pvh8h5m-oVB-PMeSvvwciTcb07itdz1SMNtri8A"